apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payment-system
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Arunkk98/paymentapp.git' # <-- Update with your GitHub username & repo name
    targetRevision: HEAD
    path: paymentapp-gitops/apps/ #  apps subfolder inside the monorepo
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: payment-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
