[master]
k8s-master-01 ansible_host=192.168.1.200

[workers]
k8s-worker-01 ansible_host=192.168.1.201
k8s-worker-02 ansible_host=192.168.1.202

[all:vars]
ansible_user=root
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_python_interpreter=/usr/bin/python3
