apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: payment-system
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5002
      protocol: TCP
      name: http
  selector:
    app: notification-service
